coverage:
  precision: 2
  round: down
  range: 75..100

  status:
    project:
      default:
        target: "75%"
    patch:
      default: off
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
