name: Packages lint
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  Packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Node.js modules cache
        uses: actions/cache@v4
        id: modules-cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-modules
      - name: Install Node.js packages
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm install
      - name: Build
        run: npm run build:packages-lib
      - name: Git modified files
        if: ${{ success() }}
        run: |
          git add --all
          echo 'GIT_MODIFIED<<EOF' >> $GITHUB_ENV
          git ls-files -m >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Lint
        if: ${{ success() }}
        uses: actions/github-script@v8
        with:
          script: |
            const action = require(`${process.env.GITHUB_WORKSPACE}/scripts/actions.fileDiffs.js`)
            const options = {
              rexp: /(packages\.js|packagesLicenses\.txt)$/,
              message: "Update packages lib with '$ npm run build:packages-lib'"
            };
            const { resultsArray, resultsString } = action(process.env.GIT_MODIFIED, options)
            if (resultsArray.length) {
              core.setFailed(resultsString)
            }
